// Code generated by goctl. DO NOT EDIT.
package types

type PietrzakReq struct {
	Name       string `json:"name"`
	Challenge  int64  `json:"challenge"`
	Iterations int    `json:"iterations"`
	Proof      string `json:"proof"`
}

type PietrzakRes struct {
	Out  string `json:"out"`
	Out2 bool   `json:"out2"`
}

type WgoReq struct {
	Name       string `json:"name"`
	Difficulty int    `json:"difficulty"`
	Input      string `json:"input"`      // string -> []byte
	InputProof string `json:"inputProof"` // string -> []byte
}

type WgoRes struct {
	Output string `json:"output"`
	Res    bool   `json:"res"`
}

type WrustReq struct {
	Name       string `json:"name"`
	Challenge  int64  `json:"challenge"`
	Iterations int    `json:"iterations"`
	Proof      string `json:"proof"`
}

type WrustRes struct {
	Out  string `json:"out"`
	Out2 bool   `json:"out2"`
}
