// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"blockchain-crypto/crypto_api/vdf/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/crypto/vdfpietrzak",
				Handler: vdf_pietrzakHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/crypto/vdfwrust",
				Handler: vdf_wrustHandler(serverCtx),
			},
		},
	)
}
