// Code generated by goctl. DO NOT EDIT.
package types

type VrfReq struct {
	Name    string `json:"name"`
	Message string `json:"message"`
	Vrf0    string `json:"vrf0"`
	Proof   string `json:"proof"`
}

type VrfRes struct {
	Vrf0  string `json:"vrf0"`
	Proof string `json:"proof"`
	Res   bool   `json:"res"`
}
