// Code generated by goctl. DO NOT EDIT.
package types

type SecretSSReq struct {
	Name   string `json:"name"` // 1,2
	N      byte   `json:"n"`
	K      byte   `json:"k"`
	Secret string `json:"secret"`
	Shares string `json:"shares"`
}

type SecretSSRes struct {
	Shares string `json:"shares"`
	Secret string `json:"secret"`
}

type SecretVssReq struct {
	Name      string `json:"name"` // 1 2 3 4
	Num       int    `json:"num"`
	T         int    `json:"t"`
	SecretNum int64  `json:"secretNum"`
	Secret    string `json:"secret"`
	Vs        string `json:"vs"`
	Shares    string `json:"shares"`
}

type SecretVssRes struct {
	Secret  string `json:"secret"`
	Vs      string `json:"vs"`
	Shares  string `json:"shares"`
	Res     bool   `json:"res"`
	Secret1 string `json:"secret1"`
}

type SecretPvssReq struct {
	Name      string `json:"name"` // 1 2 3 4
	N         int    `json:"n"`
	T         int    `json:"t"`
	X         string `json:"x"`
	H         string `json:"h"`
	Secret    string `json:"secret"`
	EncShares string `json:"encShares"`
	PubPoly   string `json:"pubPoly"`
	Xpri      string `json:"xpri"`
}

type SecretPvssRes struct {
	H         string `json:"h"`
	PubX      string `json:"pubX"`
	Prix      string `json:"prix"`
	Secret    string `json:"secret"`
	EncShares string `json:"encShares"`
	PubPoly   string `json:"pubPoly"`
	Res       bool   `json:"res"`
	Recovered string `json:"recovered"`
}
