// Code generated by goctl. DO NOT EDIT.
package types

type HashReq struct {
	HashType    string `json:"hashType"`
	HashMessage string `json:"hashMessage"`
}

type HashRes struct {
	Res []byte `json:"res"`
}
