// Code generated by goctl. DO NOT EDIT.
package types

type GenerateKeyRes struct {
	SecretA string `json:"SecretA"`
	SecretB string `json:"SecretB"`
}

type GenerateKeyEcdh struct {
	SecretA string `json:"secretA"`
	SecretB string `json:"secretB"`
}

type GenerateKeyStReq struct {
	Name      string `json:"name"` // name = req1, req2, req3
	Str1      string `json:"str1"`
	Str2      string `json:"str2"`
	Req_r     string `json:"reqr"`     // req2
	Req_pub1  string `json:"reqpub1"`  // req2
	Req_pub2  string `json:"reqpub2"`  // req2,req3
	Req_P     string `json:"reqP"`     // req3
	Req_R     string `json:"reqR"`     // req3
	Req_priv1 string `json:"reqPriv1"` // req3
	Req_priv2 string `json:"reqPriv2"` // req3
}

type GenerateKeyStRes struct {
	Priv1 string `json:"priv1"` // req1
	Pub1  string `json:"pub1"`  // req1
	Priv2 string `json:"priv2"` // req1
	Pub2  string `json:"pub2"`  // req1
	P     string `json:"p"`     // req2
	R     string `json:"r"`     // req2
	T     bool   `json:"t"`
	Priv  string `json:"priv"` // req3
}
