// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"blockchain-crypto/crypto_api/secret_sharing/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/crypto/secretss",
				Handler: SSHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/crypto/secretvss",
				Handler: VSSHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/crypto/secretpvss",
				Handler: PVSSHandler(serverCtx),
			},
		},
	)
}
